language: ruby

cache: bundler

rvm:
  - truffleruby
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
